# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rental_system
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file:
    name: logs/application-debug.log
  pattern:
    console: "%date  %highlight(%-5level) [%12.12thread] %yellow(%-40.40logger{40}) : %msg %n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO

#hibernate.generate_statistics=true
